import type { Metadata } from "next";
import { Inter } from "next/font/google";
import TopBar from "../../components/navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function AdminLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>)

{
 
  return (
    <html lang="en">

    
      <body className={inter.className}>
        <TopBar/>
        {children}
        </body>
    </html>
  );
}
